### ISSUE TITLE
400 error on @ajax decorator

### ISSUE THREAD

**Issue by awidgery** [yceruto/django-ajax#14]
Starting out with this library, and it gives me a 400 error with no information.

I'm using the exact code from the Usage section of the docs, applied to a brand new Django 1.7.2 project/app.
The dev server returns a 400 error, and the view code is never executed:

    @ajax
    def home(request):
	    print "Running"
	    pass

"Running" is not displayed on the console:

    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    [13/Jan/2015 16:26:33] "GET / HTTP/1.1" 400 0

**Comment by yceruto** [comment]
@awidgery I do not understand what to want do, but if you are using django it is best to return as a result of its function a ```string``` instead of printing. The print command is used only in console mode and tests described in the documentation are based on a http response.

Replace ```print "Running"``` by ```return "Running"``` and remove the ```pass``` statement and read https://github.com/yceruto/django-ajax#ajax-on-client-side

To learn a little more requests and responses in django see the following documentation:
https://docs.djangoproject.com/en/1.7/ref/request-response/

Thanks for using django-ajax

**Comment by awidgery** [comment]
Sorry for the misunderstanding.

I'm just trying to get the basic @ajax decorator to work at all.  `print "Running"` was to confirm that the view code was actually being called - it isn't.

As another example, if I use the exact code specified in the docs:

    @ajax
    def my_view(request):
        c = 2 + 3
        return {'result': c}

I get a straight 400 error.

Do you have any ideas how I can debug what the decorator is doing?

**Comment by yceruto** [comment]
First tries not use the decorator, returns a simple ```HttpResponse('something')``` and be sure that the status code is 200.

**Comment by yceruto** [comment]
Remember that the request must be for ajax when use ```@ajax decorator```, the status code 400 means bad request.
