### ISSUE TITLE
Static file not found

### ISSUE THREAD

**Issue by luisza** [yceruto/django-ajax#42]
Are you remove static files? 
This package is incomplete without static files.

**Comment by yceruto** [comment]
Yes, I decided remove it due to maintenance and lib purpose.

> This package is incomplete without static files.

There is today many JS libraries that can to provide ease integration with this library, but still you can use them if you want:
 * https://raw.githubusercontent.com/yceruto/django-ajax/2.3.7/django_ajax/static/django_ajax/js/jquery.ajax.min.js 
 * https://raw.githubusercontent.com/yceruto/django-ajax/2.3.7/django_ajax/static/django_ajax/js/jquery.ajax-plugin.min.js

**Comment by luisza** [comment]
Hi, I understand you about no maintenance js files but just to help other please make warning about js is not supported and also suggest some js library that can work with this package, because you lost a lot of functionality if not say that you can make a lot of things with JS and django-ajax.   A few lines can help other to see the potentially of this library
